[build]
# This default build command adds the robots noindex directive to the site headers.
# It is turned off for only for the production site by using [context.master] below
# DO NOT REMOVE THIS (contact @chenopis or @sig-docs-maintainers)
publish = "site/public"
#functions = "functions"
command = "make -C site npm git build"

[build.environment]
HUGO_VERSION = "0.60.1"

[context.production.environment]
#HUGO_BASEURL = "https://kubernetes.github.io/ingress-nginx/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"

[context.master]
publish = "site/public"
command = "make -C site npm git build"
