baseURL = "/"
title = "NGINX Ingress Controller"
theme = ["docsy"]

# SEO
enableRobotsTXT = true

# Docsy: Gives values to .Lastmod etc.
enableGitInfo = true

# Docsy: Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
# Docsy: Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Docsy: Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# privacy settings
[privacy]
  [privacy.youtube]
    # enable the cookie-less youtube in built-in hugo shortcode
    privacyEnhanced = true

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-132708785-1"

# Language configuration

[languages]
[languages.en]
title = "NGINX Ingress Controller"
description = "An open source ingress controller for Kubernetes"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS" ]
page = [ "HTML"]
section = [ "HTML"]

# Add a "text/netlify" media type for auto-generating the _headers file
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# Site params
[params]
RSSLink = "/index.xml"
copyright = "The Kubernetes Authors."

showedit = true

github_repo = "https://github.com/kubernetes/ingress-nginx"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "002375903941309441958:rceiko9wfuw"

# current release branch - could be rc
release_branch = "nginx-0.26.1"
# the main version. Never is rc.
release_version = "0.26.1"

# example tag
example_image_tag = "gcr.io/agones-images/udp-server:0.17"

# param for displaying an announcement block on every page; see PR #16210
announcement = false
# announcement_message is only displayed when announcement = true; update with your specific message
announcement_message = "The Kubernetes Documentation team would like your feedback!  Please take a <a href='https://www.surveymonkey.com/r/8R237FN' target='_blank'>short survey</a> so we can improve the Kubernetes online documentation."

# Docsy: User interface configuration
[params.ui]
# Docsy: Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Docsy: Disable the search box in the side bar.
sidebar_search_disable = true
#  Docsy: Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/kubernetes/ingress-nginx/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/kubernetes/ingress-nginx/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Slack"
	url = "https://kubernetes.slack.com"
	icon = "fab fa-slack"
    desc = "Chat with other project users in #ingress-nginx"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/IngressNGINX"
	icon = "fab fa-twitter"
    desc = "Follow us on Twitter to get the latest news!"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/kubernetes/ingress-nginx"
	icon = "fab fa-github"
    desc = "Development takes place here!"
